config/routes.rb
        match :dcv_validate, via: %i[get post]
      end
    end

    resources :invoices, only: %i[index edit update show destroy] do
      member do
        get  :download
        get  :new_payment
        get  :manage_items
        post :make_payment
        put  :remove_item
        put  :add_item
        put  :make_payment_other
        put  :refund_other
        put  :credit
        put  :update_item
        get  :transfer_items
      end
    end

    resource :user_session do
      collection do
        post :user_login
        get  :duo
        post :duo_verify
        get  :duo_verify
      end
    end

    resources :certificate_order_tokens do
      collection do
        post :request_token
      end
    end

    resources :certificate_orders do
      resources :physical_tokens do
        member do
          get :activate
        end
      end
      collection do
        get :credits
        get :pending
        get :order_by_csr
        get :incomplete
        get :reprocessing
        get :search
        get :developers
        get :show_cert_order
        post :validate_issue
        post :switch_from_comodo
        match :parse_csr, via: %i[post options]
        match :smime_client_enrollment, via: %i[get post]
      end

      member do
        get :update_csr, to: 'application#not_found', status: 404
        match :update_csr, via: %i[put patch]
        match :update_tags, via: %i[put post]
        match :recipient, via: %i[get post]
        get :download
        get :developer
        get :download_other
        get :renew
        get :reprocess
        get :auto_renew
        post :start_over
        get :sslcom_ca
        match :admin_update, via: %i[put patch]
        get :change_ext_order_number
        get :generate_cert
        post :register_domains
        get :attestation
        post :save_attestation
        post :remove_attestation
      end

      resource :validation do
        post :upload, :send_dcv_email
        match :send_to_ca, via: %i[get post]
        post :get_asynch_domains
        post :remove_domains
        post :get_email_addresses
        post :send_callback
        post :add_super_user_email
        post :request_approve_phone_number
        post :cancel_validation_process

        member do
          match :dcv_validate, via: %i[get post options]
          get :document_upload
        end
      end

      resource :site_seal
    end

    resources :certificate_contents do
      resources :attestation_certificates do
        member do
          get :server_bundle
          get :pkcs7
          get :whm_zip
          get :nginx
          get :apache_zip
          get :amazon_zip
          get :download
        end
      end
      resources :contacts, only: :index
      match :update_tags, via: %i[put post], on: :member
    end

    resources :contacts, except: :index do
      collection do
        get :saved_contacts
      end
    end

    resources :csrs do
      resources :signed_certificates do
        member do
          get :server_bundle
          get :pkcs7
          get :whm_zip
          get :nginx
          get :apache_zip
          get :amazon_zip
          get :download
        end
      end
      collection do
        get :country_codes
        post :all_domains
        post :check_validation
      end

      member do
        get :http_dcv_file
        get :verification_check
        post :create_new_unique_value
      end
    end

    resources :managed_csrs do
      collection do
        get :show_csr_detail
        post :add_generated_csr
        post :remove_managed_csrs
      end
    end

    resources :notification_groups do
      resources :scan_logs, only: :index

      collection do
        get :certificate_orders_domains_contacts
        get :search
        post :register_notification_group
        post :remove_groups
        post :scan_groups
        post :scan_individual_group
        post :change_status_groups
        post :check_duplicate
      end
    end

    resources :registered_agents do
      collection do
        post :search
        post :remove_agents
        post :approve_ssl_managers
        post :approve_ssl_manager
      end

      member do
        get :managed_certificates
        post :search_managed_certificates
        post :remove_managed_certificates
      end
    end

    resources :other_party_validation_requests, only: %i[create show]

    resources :validation_histories
    resources :validations, only: %i[index update] do
      collection do
        get :search, :requirements, :domain_control, :ev, :organization
        post :upload_for_registrant
      end
    end
    resources :site_seals, only: %i[index update admin_update] do
      collection do
        get :details
        get :search
      end
      member do
        get :site_report
        get :artifacts
        match :admin_update, via: %i[put patch]
      end
    end

    resources :orders do
      collection do
        get :checkout, action: 'new' # this shows the discount code prompt
        get :show_cart
        post :add_cart
        get :search
        get :visitor_trackings
        post :create_free_ssl
        post :create_multi_free_ssl
        post :lookup_discount
        post :smime_client_enroll_create
        post :ucc_domains_adjust_create
        post :change_quantity_in_cart
      end
      member do
        get :invoice
        get :refund
        get :revoke
        get :change_state
        get :refund_merchant
        match :update_invoice, via: %i[put post]
        match :transfer_order, via: %i[put post]
        match :update_tags, via: %i[put post]
      end
    end
    resources :billing_profiles

    resource :ssl_account do
      get :edit_settings
      get :validate_ssl_slug
      match :update_settings, via: %i[put patch]
      match :update_ssl_slug, via: %i[put patch]
      match :update_company_name, via: %i[put patch]
      collection do
        post :register_duo
        put  :duo_enable
        put  :duo_own_used
        put  :set_2fa_type
        post :remove_reseller
        post :manage_reseller
      end
      member do
        get :adjust_funds
      end
    end

    resources :users, only: :index do
      match :enable_disable, via: %i[put patch], on: :member
      match :enable_disable_duo, via: %i[put patch], on: :member
    end

    resources :api_credentials do
      member do
        patch 'update_roles'
        get   'remove'
      end
    end

    resource :api_credential do
      collection do
        post :reset_credential
      end
    end

    resource :account, controller: :users do
      resource :reseller
    end

    resources :managed_users, only: %i[new create edit] do
      member do
        patch 'update_roles'
        get   'remove_from_account'
      end
    end

    resources :cdns do
      post :register_account, on: :collection
      # post :register_api_key, on: :collection
      delete :delete_resources, on: :collection
      get :check_cname, on: :collection

      member do
        get :resource_cdn
        patch :update_resource
        post :add_custom_domain
        post :update_custom_domain
        post :update_advanced_setting
        delete :delete_resource
        delete :purge_cache
        post :update_cache_expiry
      end
    end

    get '/orders/filter_by_state/:id' => 'orders#filter_by_state', as: :filter_by_state_orders
    match '/validation_histories/:id/documents/:style.:extension' => 'validation_histories#documents', :as => :validation_document, style: /.+/i, via: %i[get post]
    get 'certificate_orders/filter_by/:id' => 'certificate_orders#filter_by', as: :filter_by_certificate_orders
    get 'certificate_orders/filter_by_scope/:id' => 'certificate_orders#filter_by_scope', as: :filter_by_scope_certificate_orders
    match 'get_free_ssl' => 'funded_accounts#create_free_ssl', :as => :create_free_ssl, via: %i[get post]
    match 'secure/allocate_funds' => 'funded_accounts#allocate_funds', :as => :allocate_funds, via: %i[get post]
    match 'secure/allocate_funds_for_order/:id' => 'funded_accounts#allocate_funds_for_order', :as => :allocate_funds_for_order, via: %i[get post]
    match 'secure/deposit_funds' => 'funded_accounts#deposit_funds', :as => :deposit_funds, via: %i[get put patch post]
    match 'secure/confirm_funds/:id' => 'funded_accounts#confirm_funds', :as => :confirm_funds, via: %i[get post]
    match 'secure/apply_funds' => 'funded_accounts#apply_funds', :as => :apply_funds, via: %i[get post put]
    match 'users/new/affiliates' => 'users#new', :as => :affiliate_signup, via: %i[get post]
    match 'affiliates/:affiliate_id/orders' => 'orders#affiliate_orders', :as => :affiliate_orders, via: %i[get post]
    match ':user_id/orders' => 'orders#user_orders', :as => :user_orders, via: %i[get post]

    match 'paypal_express/checkout', via: %i[get post]
    match 'paypal_express/review', via: %i[get post]
    match 'paypal_express/purchase', via: %i[get post]

    match "/site_seals/:id/site_report'," => 'site_seals#site_report', via: :get

    # mailbox
    get 'mail/inbox' => 'mailbox#inbox', as: :mail_inbox
    get 'mail/sent' => 'mailbox#sent', as: :mail_sent
    get 'mail/trash' => 'mailbox#trash', as: :mail_trash
    match 'mail/compose' => 'mailbox#compose', as: :mail_compose, via: %i[get post]
    get 'mail/read' => 'mailbox#read', as: :mail_read
    put 'mail/reply' => 'mailbox#reply', as: :mail_reply
    put 'mail/move_to_trash' => 'mailbox#move_to_trash', as: :mail_move_to_trash
  end

  scope '(/team/:ssl_slug)', module: false do
    concerns :teamable
  end

  # User verifications, eg OTP
  resources :verifications
  resources :otps do
    collection do
      get :email
      get :email_login
      get :login
      post :verify_login
      get :add_phone
      post :verify_add_phone
    end
  end

  resources :u2fs do
    collection do
      post :verify
    end
  end

  resources :users, except: :index do
    collection do

app/models/concerns/certificate_name/verification.rb
module Concerns
  module CertificateName
    module Verification
      extend ActiveSupport::Concern

      def dcv_verify(protocol = nil)
        attempts = protocol&.match?(/^acme/i) ? 0 : 2
        status = while attempts < 3
                   response = attempt_dcv(protocol)
                   break response if response

                   attempts += 1
                   sleep 5 if attempts < 3
                 end
        if status == true
          satisfy_dcv
        else
          fail_dcv
        end
      end

      def dcv_verify_async(dcv)
        if dcv_verify(dcv.dcv_method)
          dcv.satisfy! unless dcv.satisfied?
        end
      end
      handle_asynchronously :dcv_verify_async

      def attempt_dcv(protocol)
        case protocol ||= domain_control_validation&.dcv_method
        when /email/
          false
        when /acme_http/i
          AcmeManager::HttpVerifier.new(api_credential.acme_acct_pub_key_thumbprint, acme_token, non_wildcard_name(true)).call
        when /acme_dns_txt/i
          AcmeManager::DnsTxtVerifier.new(api_credential.acme_acct_pub_key_thumbprint, non_wildcard_name(true)).call
        else
          self.class.dcv_verify(protocol, verification_options) if csr.present?
        end
      end

      def satisfy_dcv
        true
      end

      def fail_dcv
        false
      end

      def verification_options(prepend = '')
        { https_dcv_url: dcv_url(true, prepend, true),
          http_dcv_url: dcv_url(false, prepend, true),
          cname_origin: cname_origin(true),
          cname_destination: cname_destination,
          csr: csr,
          ca_tag: ca_tag }
      end

      def api_credential
        certificate_content&.ssl_account&.api_credential
      end

      included do
        def self.dcv_verify(protocol, options)
          begin
            wait_period = protocol&.match?(/^acme/i) ? 5 : 0
            @options = options
            Timeout.timeout(Surl::TIMEOUT_DURATION + (wait_period * 3)) do
              verify(protocol)
            end
          rescue Exception => _e
            false
          end
        end

        def self.options
          @options
        end

        def self.response
          @response
        end

        def self.verify(protocol)
          @response = case protocol
                      when /https/
                        https_verify(options[:https_dcv_url])
                      when /cname/
                        cname_verify(options[:cname_origin], options[:cname_destination])
                      else
                        http_verify(options[:http_dcv_url])
                      end
          response == true || verified
        end

        def self.https_verify(https_dcv_url)
          uri = URI.parse(https_dcv_url)
          http = Net::HTTP.new(uri.host, uri.port)
          http.use_ssl = true
          http.verify_mode = OpenSSL::SSL::VERIFY_NONE
          request = Net::HTTP::Get.new(uri.request_uri)
          http.request(request).body
        end

        def self.cname_verify(cname_origin, cname_destination)
          txt = Resolv::DNS.open do |dns|
            dns.getresources(cname_origin, Resolv::DNS::Resource::IN::CNAME)
          end
          txt&.size&.positive? && cname_destination.casecmp(txt.last.name.to_s).zero?
        end

        def self.http_verify(http_dcv_url)
          uri = URI.parse(http_dcv_url)
          response = uri.open('User-Agent' => I18n.t('users_agent.chrome'), redirect: true)
          response.read
        end

        def self.verified
          !!(sha2_hash_matches? && ca_tag_valid? && unique_value_accepted?)
        end

        def self.ca_tag
          options[:ca_tag]
        end

        def self.csr
          options[:csr]
        end

        def self.has_ssl_ca_tag?
          ca_tag == I18n.t('labels.ssl_ca')
        end

        def self.sha2_hash_matches?
          response.match? Regexp.new("^#{options[:csr].sha2_hash}")
        end

        def self.unique_value_not_considered?
          csr.unique_value.blank? || options[:ignore_unique_value].presence || false
        end

        def self.unique_value_accepted?
          unique_value_not_considered? || unique_value_matches?
        end

        def self.unique_value_matches?
          response.match? Regexp.new("^#{options[:csr].unique_value}")
        end

        def self.ca_tag_valid?
          has_ssl_ca_tag? || has_matching_external_ca_tag?
        end

        def self.has_matching_external_ca_tag?
          response.match? Regexp.new("^#{options[:ca_tag]}")
        end

        def has_unique_value_from_csr?
          response.match? Regexp.new("^#{csr.unique_value}")
        end
      end
    end
  end
end

app/models/verification.rb
class Verification < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true
  # Validate existence of prefix when phone exists
  validates :call_prefix, presence: true, if: -> { call_number.present? }
  validates :sms_prefix, presence: true, if: -> { sms_number.present? }
  validate :minimum_one_method

  def minimum_one_method
    errors.add(:base, 'at least one verification method required') if email.nil? && call_number.nil? && sms_number.nil?
  end
end

app/controllers/verifications_controller.rb
# frozen_string_literal: true

class  VerificationsController < ApplicationController
  before_action :current_user
  before_action :require_user

  def index; end
end

app/views/verifications/_index_scripts.html.erb
<script type="text/javascript">
jQuery.noConflict();
jQuery(function($) {
  $(document).ready(function() {
    // Edit phone number
    $(document).on('click', 'button[id="edit-phone"]', function() {
      $('#edit-phone').hide();
      $('#user_phone').prop('disabled', false);
      $('#user_phone').focus();
    });
    // OTP
    // Send SMS when user submits phone
    var add_phone_otp_url = '<%= add_phone_otps_path %>';
    $('#submit_phone_verification, a#resend-otp-phone').click(function(event) {
      $('#phone-error').hide(); // Hide in case there were errors before
      $('#code-error').hide();
      if($('#user_phone').val() == '') {
        alert('Please fill in your phone number');
      }
      else {
        $.ajax({
        url: add_phone_otp_url,
        data: {
          otp: {
            phone: $('#user_phone').val(),
            phone_prefix: $('#country-code-0').val()
          }
        },
        type: 'GET',
        success: function(result) {
          if(result['error']){
            $('#phone-error').show();
            $('#phone-error').text(result['error']);
            $('#phone-error').css('color', 'red');
          } else if (result['id']) {
            $('#code-verification-fields').show();
            $('#send-otp').hide();
            $('#phone-error').hide(); // Hide in case there were errors before
            // Value for authy_user in form hidden field, to be used in verification
            $('#otp_authy_user').val(result['id']);
          }
        }
      });
      }
    });

    var email_otp_url = '<%= email_otps_path %>';
    $('a#otp-email, a#resend-otp-email').click(function(event) {
      $('#phone-error').hide(); // Hide in case there were errors before
      $('#code-error').hide();
      $.ajax({
        url: email_otp_url,
        data: {
          otp: {
            phone: $('#user_phone').val(),
            phone_prefix: $('#country-code-0').val()
          }
        },
        type: 'GET',
        success: function(result) {
          if(result['error']){
            $('#phone-error').show();
            $('#phone-error').text(result['error']);
            $('#phone-error').css('color', 'red');
          } else {
            $('#code-verification-fields').removeClass('hidden');
            $('#submit_phone_verification').hide();
            $('#otp-email').hide();
            $('#phone-error').hide(); // Hide in case there were errors before
            // Value for authy_user in form hidden field, to be used in verification
            $('#otp_authy_user').val(result['id']);
          }
        }
      });
    });

    // Verify OTP
    var verify_otp_url = '<%= verify_add_phone_otps_path %>';
    $('#code_submit').click(function(event){
      $('#code-error').hide();
      $.ajax({
        url: verify_otp_url,
        data: {
          otp: {
            verification_code: $('#otp_verification_code').val(),
            authy_user: $('#otp_authy_user').val(),
            phone: $('#user_phone').val(),
            phone_prefix: $('#country-code-0').val()
          }
        },
        type: 'POST',
        success: function(result) {
          if(result['error']){
            $('#code-error').show();
            $('#code-error').text(result['error']);
            $('#code-error').css('color', 'red');
          } else if (result['success'] == 'true' ) {
            $('#phone-error').show();
            $('#phone-error').text('Verified!');
            $('#phone-error').css('color', 'green');
            $('#phone-hint').hide();
            $('#code-verification-fields').hide();
          }
        }
      });
    })
  });
});
</script>

app/views/verifications/index.html.haml
= javascript_include_tag '//stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js'
= stylesheet_link_tag 'bootstrap_style', media: 'all'
= stylesheet_link_tag 'bootstrap_fix'
= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/authy-form-helpers/2.3/form.authy.min.css', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/authy-form-helpers/2.3/form.authy.min.js', 'data-turbolinks-track': 'reload'
= render partial: 'index_scripts'
- @title = "Verify Account"
- content_for :title, @title

.container
  .row
    .col-md-12
      .page-header
        %h4.text-center
          Verify Account
        %h4.text-center
          If you lose your security key, we will send you a code via email or SMS
        %hr
  - selected_country = ISO3166::Country.find_country_by_country_code(current_user&.phone_prefix) || ISO3166::Country.find_country_by_alpha2('US')

  .card
    .card-body
    .row
      .col-md-2
        %label
          %h4.text-right Phone
      .col-10
        .input-group
          = select_tag "authy-countries", nil, name: 'country_code', 'data-show-as': 'number', 'data-value': selected_country.country_code
          = text_field_tag :phone, current_user&.phone, { id: 'user_phone', autofocus: true, disabled: current_user.phone.present? }
          - if current_user.phone.present?
            = button_tag 'Edit', type: 'button', id: 'edit-phone'

      .col-md-10.offset-md-2
        %h5#phone-hint
          We will send you a code via SMS on this number
        %span.clearfix
          #phone-error
        %p#send-otp
          %br
          = button_tag 'Save and Verify Phone Number', id: 'submit_phone_verification', class: 'btn btn-secondary btn-lg'
          = link_to "Or send via email to #{current_user.email}", '#', id: 'otp-email'
    .row.hidden#code-verification-fields
      .col-md-2
        %h4.text-right Enter verification code
      .col-md-10
        = text_field_tag 'otp_verification_code', nil, autofocus: true, class: 'col-3 form-control'
        %span.clearfix
          #code-error
        %h4= link_to "Resend via SMS to #{current_user.phone}", '#', id: 'resend-otp-phone'
        %h4= link_to "Resend via email to #{current_user.email}", '#', id: 'resend-otp-email'
        = hidden_field_tag 'otp_authy_user', @authy_user
        .clearfix
        %h4= button_tag "Verify Code", id: 'code_submit', class: 'btn btn-lg btn-secondary'
  .row
    .col-12
      %p= link_to 'Manage Hardware Tokens', u2fs_path, class: 'btn btn-light'

// OTP creation should create user.verification