config/routes.rb
      collection do
        get :show_csr_detail
        post :add_generated_csr
        post :remove_managed_csrs
      end
    end

    resources :notification_groups do
      resources :scan_logs, only: :index

      collection do
        get :certificate_orders_domains_contacts
        get :search
        post :register_notification_group
        post :remove_groups
        post :scan_groups
        post :scan_individual_group
        post :change_status_groups
        post :check_duplicate
      end
    end

    resources :registered_agents do
      collection do
        post :search
        post :remove_agents
        post :approve_ssl_managers
        post :approve_ssl_manager
      end

      member do
        get :managed_certificates
        post :search_managed_certificates
        post :remove_managed_certificates
      end
    end

    resources :other_party_validation_requests, only: %i[create show]

    resources :validation_histories
    resources :validations, only: %i[index update] do
      collection do
        get :search, :requirements, :domain_control, :ev, :organization
        post :upload_for_registrant
      end
    end
    resources :site_seals, only: %i[index update admin_update] do
      collection do
        get :details
        get :search
      end
      member do
        get :site_report
        get :artifacts
        match :admin_update, via: %i[put patch]
      end
    end

    resources :orders do
      collection do
        get :checkout, action: 'new' # this shows the discount code prompt
        get :show_cart
        post :add_cart
        get :search
        get :visitor_trackings
        post :create_free_ssl
        post :create_multi_free_ssl
        post :lookup_discount
        post :smime_client_enroll_create
        post :ucc_domains_adjust_create
        post :change_quantity_in_cart
      end
      member do
        get :invoice
        get :refund
        get :revoke
        get :change_state
        get :refund_merchant
        match :update_invoice, via: %i[put post]
        match :transfer_order, via: %i[put post]
        match :update_tags, via: %i[put post]
      end
    end
    resources :billing_profiles

    resource :ssl_account do
      get :edit_settings
      get :validate_ssl_slug
      match :update_settings, via: %i[put patch]
      match :update_ssl_slug, via: %i[put patch]
      match :update_company_name, via: %i[put patch]
      collection do
        post :register_duo
        put  :duo_enable
        put  :duo_own_used
        put  :set_2fa_type
        post :remove_reseller
        post :manage_reseller
      end
      member do
        get :adjust_funds
      end
    end

    resources :users, only: :index do
      match :enable_disable, via: %i[put patch], on: :member
      match :enable_disable_duo, via: %i[put patch], on: :member
    end

    resources :api_credentials do
      member do
        patch 'update_roles'
        get   'remove'
      end
    end

    resource :api_credential do
      collection do
        post :reset_credential
      end
    end

    resource :account, controller: :users do
      resource :reseller
    end

    resources :managed_users, only: %i[new create edit] do
      member do
        patch 'update_roles'
        get   'remove_from_account'
      end
    end

    resources :cdns do
      post :register_account, on: :collection
      # post :register_api_key, on: :collection
      delete :delete_resources, on: :collection
      get :check_cname, on: :collection

      member do
        get :resource_cdn
        patch :update_resource
        post :add_custom_domain
        post :update_custom_domain
        post :update_advanced_setting
        delete :delete_resource
        delete :purge_cache
        post :update_cache_expiry
      end
    end

    get '/orders/filter_by_state/:id' => 'orders#filter_by_state', as: :filter_by_state_orders
    match '/validation_histories/:id/documents/:style.:extension' => 'validation_histories#documents', :as => :validation_document, style: /.+/i, via: %i[get post]
    get 'certificate_orders/filter_by/:id' => 'certificate_orders#filter_by', as: :filter_by_certificate_orders
    get 'certificate_orders/filter_by_scope/:id' => 'certificate_orders#filter_by_scope', as: :filter_by_scope_certificate_orders
    match 'get_free_ssl' => 'funded_accounts#create_free_ssl', :as => :create_free_ssl, via: %i[get post]
    match 'secure/allocate_funds' => 'funded_accounts#allocate_funds', :as => :allocate_funds, via: %i[get post]
    match 'secure/allocate_funds_for_order/:id' => 'funded_accounts#allocate_funds_for_order', :as => :allocate_funds_for_order, via: %i[get post]
    match 'secure/deposit_funds' => 'funded_accounts#deposit_funds', :as => :deposit_funds, via: %i[get put patch post]
    match 'secure/confirm_funds/:id' => 'funded_accounts#confirm_funds', :as => :confirm_funds, via: %i[get post]
    match 'secure/apply_funds' => 'funded_accounts#apply_funds', :as => :apply_funds, via: %i[get post put]
    match 'users/new/affiliates' => 'users#new', :as => :affiliate_signup, via: %i[get post]
    match 'affiliates/:affiliate_id/orders' => 'orders#affiliate_orders', :as => :affiliate_orders, via: %i[get post]
    match ':user_id/orders' => 'orders#user_orders', :as => :user_orders, via: %i[get post]

    match 'paypal_express/checkout', via: %i[get post]
    match 'paypal_express/review', via: %i[get post]
    match 'paypal_express/purchase', via: %i[get post]

    match "/site_seals/:id/site_report'," => 'site_seals#site_report', via: :get

    # mailbox
    get 'mail/inbox' => 'mailbox#inbox', as: :mail_inbox
    get 'mail/sent' => 'mailbox#sent', as: :mail_sent
    get 'mail/trash' => 'mailbox#trash', as: :mail_trash
    match 'mail/compose' => 'mailbox#compose', as: :mail_compose, via: %i[get post]
    get 'mail/read' => 'mailbox#read', as: :mail_read
    put 'mail/reply' => 'mailbox#reply', as: :mail_reply
    put 'mail/move_to_trash' => 'mailbox#move_to_trash', as: :mail_move_to_trash
  end

  scope '(/team/:ssl_slug)', module: false do
    concerns :teamable
  end

  # User verifications, eg OTP
  resources :verifications
  resources :otps do
    collection do
      get :email
      get :email_login
      get :login
      post :verify_login
      get :add_phone
      post :verify_add_phone
    end
  end

  resources :u2fs do
    collection do
      post :verify
    end
  end

  resources :users, except: :index do
    collection do
      get :edit_password
      get :edit_email
      match :resend_activation, via: %i[get post]
      get :activation_notice
      get :search
      get :cancel_reseller_signup
      match :enable_disable, via: %i[put patch]
      match :enable_disable_duo, via: %i[put patch]
      get :show_user
      get :reset_failed_login_count
      match :upload_avatar, format: /(js|json)/, via: %i[put patch]
      get :avatar, format: /(js|json)/
    end

    member do
      get   :edit_password
      get   :edit_email
      get   :login_as
      match :admin_update, via: %i[put patch]
      get   :admin_show
      get   :dup_info
      post  :consolidate
      get   :adjust_funds
      get   :change_login
      get   :switch_default_ssl_account
      get   :approve_account_invite
      get   :resend_account_invite
      get   :decline_account_invite
      get   :teams
      get   :search_teams
      match :create_team, via: %i[get post]
      put   :set_default_team
      match :set_default_team_max, via: %i[put patch]
      match :admin_activate, via: %i[put patch]
      get   :leave_team
      get   :dont_show_again
      get   :duo
      match :duo_verify, via: %i[get post]
      get   :archive_team
      get   :retrieve_team
    end
  end

  resources :apis
  match '/certificates/pricing', to: 'certificates#pricing', as: :certificate_pricing, via: %i[get post]
  resources :certificates do
    collection do
      get :single_domain
      get :wildcard_or_ucc
      get :admin_index
    end
    member do
      get :buy
      get :buy_renewal
      match :manage_product_variants, via: %i[get post]
    end
  end

  scope '(/team/:ssl_slug)' do
    resources :phone_callbacks, only: [:create] do
      get 'approvals', on: :collection
      get 'verifications', on: :collection
    end
  end

  match '/contacts/:id/admin_update' => 'contacts#admin_update', as: :admin_update_contact, via: %i[put post]
  match '/ssl_manager/:id/approve' => 'registered_agents#approve', :as => :approve_ssl_manager, via: [:get]
  match '/activate/:id' => 'activations#create', :as => :activate, via: %i[get post]
  match '/register/:activation_code' => 'activations#new', :as => :register, via: %i[get post]
  match '/sitemap.xml' => 'site#sitemap', :as => :sitemap, via: %i[get post]
  match 'reseller' => 'site#reseller', :as => :reseller, :constraints => { subdomain: Reseller::SUBDOMAIN }, via: %i[get post]
  match '/subject_alternative_name' => 'site#subject_alternative_name', as: :san, via: %i[get post]
  match 'browser_compatibility' => 'site#compatibility', as: :browsers, via: %i[get post]
  match 'acceptable-top-level-domains-tlds-for-ssl-certificates' => 'site#top_level_domains_tlds', as: :tlds, via: %i[get post]
  match '/certificate_order_token/:token/generate_cert' => 'certificate_orders#generate_cert', :as => :confirm, via: [:get]
  match '/download_certificates/:co_ids' => 'certificate_orders#download_certificates', as: :download_certificates, via: [:post], defaults: { format: :csv }
  match '/validation/email_verification_check' => 'validations#email_verification_check', :as => :email_verification_check, via: [:post]

  # Callback
  match '/callback/:token' => 'validations#verification', :as => :email_verification, via: [:get]
  match '/validation/automated_call' => 'validations#automated_call', :as => :automated_call, via: [:post]

app/models/cdn.rb
class Cdn < ApplicationRecord
  include Pagable

  belongs_to :ssl_account
  belongs_to :certificate_order
end

app/views/cdns/_index_scripts.html.erb
<script type="text/javascript">
  jQuery.noConflict();
  jQuery(function($) {
    $(document).ready(function() {
      $('#number_rows').change(function() {
        $('#per_page').val($(this).val());
        $('#hidden_form').submit();
      });

      $('.chk-delete').click(function() {
        if ($(this).prop('checked')) {
          $('#btn_update_resource').attr('disabled', false);
        } else {
          var chk_delete_list = $('.chk-delete');
          var exist_chk = false;

          $.each(chk_delete_list, function(idx, chk_delete) {
            if ($(chk_delete).prop('checked')) {
              exist_chk = true;
              return false;
            }
          });

          exist_chk ? $('#btn_update_resource').attr('disabled', false) : $('#btn_update_resource').attr('disabled', true);
        }
      });
      $("#generate_install_ssl_chk").change(function() {
        if ($(this).prop('checked')) {
          $("#custom_domain_modal_form").hide();
          $(".gen-install-ssl-divider").hide();
          $("#generate_type").val("auto");

          $('.modify-custom-domain').attr('disabled', false);
        } else {
          $("#custom_domain_modal_form").show();
          $(".gen-install-ssl-divider").show();
          $("#generate_type").val("manual");

          /*$('.modify-custom-domain').attr('disabled', true);*/
          $.check_manual_ssl();
        }
      });

      $.check_manual_ssl = function() {
        if ($('#certificate_value').val() == "" && $('#private_key').val() == "") {
          $('.modify-custom-domain').attr('disabled', true);
        } else {
          $('.modify-custom-domain').attr('disabled', false);
        }
      };

      $('#private_key').bind('cut copy', function (e) {
        e.preventDefault();
      });
      $('#private_key').on('contextmenu',function(e) {
        return false;
      });

      $('#certificate_value').bind('change paste', function() {
        $.check_manual_ssl();
      });
      $('#certificate_value').blur(function() {
        $.check_manual_ssl();
      });

      $('#private_key').bind('change paste', function() {
        $.check_manual_ssl();
      });
      $('#private_key').blur(function() {
        $.check_manual_ssl();
      });

      $('#purge_all_btn').click(function() {
        $('form #purge_all').val(true);
        $('#purge_form').submit();
      });

      $('.custom-domain-modal-link').click(function() {
        var hostname = $(this).data('hostname');
        var ref = $(this).data('ref');
        var resourcename = $(this).data('resourcename');
        var ajaxCheckCnameUrl = '<%=check_cname_cdns_path%>';

        $.ajax({
          url: ajaxCheckCnameUrl,
          data: {
            custom_domain: hostname,
            resource_name: resourcename
          },
          type: "GET",
          success: function(result) {
            if ($('#content').find('.inner').children().first().hasClass('flash_message')) {
              $('#content').find('.inner').children().first().remove();
            }

            if (result == true) {
              $('#host_name').val(hostname);
              $('#custom_domain_ref').val(ref);
              $('#custom-domain-modal').modal('toggle');
            } else {
              var message_wrap_element = $('<div></div>');
              message_wrap_element.attr('class', 'flash_message error');

              var message_element = $('<span></span>');
              message_element.html('CNAME for <strong>' + hostname + ' -> ' + resourcename + '.a.cdnify.io</strong> not detected, Autoinstall SSL requires this CNAME');
              message_wrap_element.append(message_element);

              var btn_element = $('<small></small>');
              var close_btn_element = $('<div></div>');
              close_btn_element.attr('class', 'close_flash_message');

              var close_sign_element = $('<span></span>');
              close_sign_element.append('X');

              close_btn_element.append(close_sign_element);
              close_btn_element.append('close');

              btn_element.append(close_btn_element);
              message_wrap_element.append(btn_element);

              message_wrap_element.insertBefore($('#content').find('.inner').children().first());
            }
          }
        });

        return false;
      });

      $('.custom-domain-delete-link').click(function() {
        var hostname = $(this).data('hostname');
        $('#host_name').val(hostname);
        $('.delete-custom-domain').trigger('click');
        return false;
      });

      $('.delete-custom-domain').click(function() {
        $('#action_type').val('delete');
        $('form#custom_domain_modal_form').submit();
      });

      $('.modify-custom-domain').click(function() {
        $('.modify-custom-domain').attr('disabled', true);
        $('.cancel-custom-domain').attr('disabled', true);
        $('.delete-custom-domain').attr('disabled', true);

        if ($("#generate_install_ssl_chk").prop('checked')) {
          $('#certificate_value').val('');
          $('#private_key').val('');
        }

        $('form#custom_domain_modal_form').submit();
      });

      $('.btn_purge_file').click(function() {
        var file_uri = $(this).data('file');
        $('#purge_files').val(file_uri);
        $('#purge_form').submit();
      });

      $('#btn_create_resource').click(function() {
        var api_key = $('form#create_resource #api_key').val();
        if (api_key) {
          var res_ori = $('form#create_resource #resource_origin').val();
          var res_name = $('form#create_resource #resource_name').val();

          if (res_ori == '' || res_name == '') {
            if ($('#content').find('.inner').children().first().hasClass('flash_message')) {
              $('#content').find('.inner').children().first().remove();
            }

            var message_wrap_element = $('<div></div>');
            message_wrap_element.attr('class', 'flash_message error');

            var message_element = $('<span></span>');
            if (res_ori == '') {
              message_element.append('<li>Resource Origin is required.</li>');
            }
            if (res_name == '') {
              message_element.append('<li>Resource Name is required.</li>');
            }
            message_wrap_element.append(message_element);

            var btn_element = $('<small></small>');
            var close_btn_element = $('<div></div>');
            close_btn_element.attr('class', 'close_flash_message');

            var close_sign_element = $('<span></span>');
            close_sign_element.append('X');

            close_btn_element.append(close_sign_element);
            close_btn_element.append('close');

            btn_element.append(close_btn_element);
            message_wrap_element.append(btn_element);

            message_wrap_element.insertBefore($('#content').find('.inner').children().first());

            return false;
          }
        } else {
          $('#tos-modal #agree_tos_chk').attr('checked', false);
          $('#tos-modal .agree-cdn-tos').prop('disabled', 'disabled');
          $('#tos-modal').modal('toggle');
          return false;
        }
      });

      $('#agree_tos_chk').click(function() {
        var is_agree = $(this).prop('checked');
        if (is_agree) {
          $('.agree-cdn-tos').prop('disabled', '');
        } else {
          $('.agree-cdn-tos').prop('disabled', 'disabled');
        }
      });

      $('.agree-cdn-tos').click(function() {
        $(this).attr('disabled', 'disabled');
        var ajaxActivateCDNUrl = '<%=register_account_cdns_path%>';
        $.ajax({
          url: ajaxActivateCDNUrl,
          type: "POST",
          success: function(data) {
            if (data['error']) {
              if ($('#content').find('.inner').children().first().hasClass('flash_message')) {
                $('#content').find('.inner').children().first().remove();
              }

              var message_wrap_element = $('<div></div>');
              message_wrap_element.attr('class', 'flash_message error');

              var message_element = $('<span></span>');
              message_element.append(data['error']);
              message_wrap_element.append(message_element);

              var btn_element = $('<small></small>');
              var close_btn_element = $('<div></div>');
              close_btn_element.attr('class', 'close_flash_message');

              var close_sign_element = $('<span></span>');
              close_sign_element.append('X');

              close_btn_element.append(close_sign_element);
              close_btn_element.append('close');

              btn_element.append(close_btn_element);
              message_wrap_element.append(btn_element);

              message_wrap_element.insertBefore($('#content').find('.inner').children().first());

              $('#tos-modal').modal('toggle');
            } else {
              $('#tos-modal').modal('toggle');
              $('form#create_resource #api_key').val(data['api_key']);
              $('#btn_create_resource').trigger('click');
            }
          }
        });
      });

    });
  });
</script>

app/views/cdns/index.html.haml
-title = "CDN Management"
-content_for :title, title
=render :partial => 'index_scripts'
=javascript_include_tag '//stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js'
=stylesheet_link_tag "bootstrap_fix", :media => 'all'
-resources = @results[:resources]
#search_bar.hidden
  =form_tag :cdns, :id=>'hidden_form', :method=>:get do
    =hidden_field_tag :per_page, @per_page
#cdns
  %hr
  %div
    .sub-title
      CDN Resources (read
      =link_to "How to Boost Site Speeds", "https://www.ssl.com/how-to/boost-website-speed-with-ssl-com-cdn/"
      and
      =link_to "How Do I Create a CDN?", "https://www.ssl.com/article/what-is-a-cdn-and-how-can-i-get-one-from-ssl-com/"
      )
    .sub-cont
      =form_tag :delete_resources_cdns, :method=>:delete do
        =hidden_field_tag :api_key, @current_user_api_key
        #resources
          %table(cellspacing="0")
            -if resources && resources.length > 0
              %tfoot
                %tr
                  %td.wrap_number_rows(colspan='2')
                    =select_tag :number_rows,
                    options_for_select([[5, 5], [10, 10], [20, 20], [50, 50], [100, 100]], @per_page),
                    :class=>'per_page'
                  %td(colspan='4')=will_paginate resources
            %caption
              CDN Resources Management
              =will_paginate resources
            %tr.heading_row
              %th Hostname
              %th Origin
              %th Custom Host Name
              %th Created
              %th Delete?
            -if resources && resources.length > 0
              -resources.each do |resource|
                -owner_key = resource['user_api_key'] ? resource['user_api_key'] : @current_user_api_key
                %tr
                  %td
                    =link_to resource['hostname'], resource_cdn_cdn_path(@ssl_slug, resource['id'])
                  %td
                    =resource['origin']
                  %td
                    -if resource['custom_domains'].size > 0
                      -resource['custom_domains'].each do |custom_domain|
                        %p=custom_domain['hostname']
                    -else
                      %span ---
                  %td
                    =DateTime.parse(resource['created_at']).strftime("%d/%m/%Y")
                  %td
                    =check_box_tag "deleted_resources[]", resource['id'] + '|' + resource['alias'] + '|' + owner_key, false, class: 'chk-delete'
            -else
              %tr
                %td(colspan="5")
                  There are no resources
          -if resources && resources.length > 0
            =submit_tag 'Save', :id=>'btn_update_resource', :disabled=>true
    %hr
    %div.create-resource
      .sub-title Create Resource
      .sub-cont
        =form_tag '', :id=>'create_resource', :method=>:post do
          =hidden_field_tag :api_key, @current_user_api_key
          %div.reg-resource.clearfix
            .field-label * Resource Origin:
            .field-cont
              =text_field_tag :resource_origin, nil, placeholder: 'http://www.yoursite.com'
              .note
                Which website should we mirror on the CDN?
          %div.reg-resource.clearfix
            .field-label * Resource Name:
            .field-cont
              =text_field_tag :resource_name, nil, placeholder: 'mysite'
              %span .a.cdnify.io
              .note
                Something to identify this resource by (e.g. mysite.a.cdnify.io)
          =submit_tag 'Create', :id=>'btn_create_resource'
    %hr
  %div.modal#tos-modal
    %div.modal-dialog
      %div.modal-content
        %div.modal-header
          %h4.modal-title#modal-label Activate CDN
          %button.close{:type => 'button', 'data-dismiss' => 'modal'}
            #span &times
        %div.modal-body
          %div.container-fluid
            .row
              =text_area_tag :agreement, render(file: "public/agreements/cdnify.txt"), :size=>"100x20", :readonly=>true
            .row.pt-3
              %label
                =check_box_tag :agree_tos_chk, false
                I agree to CDNify's "Terms of Service" above
        %div.modal-footer
          %div.container-fluid
            %div.row
              .col-12
                =button_tag 'Save', 'class' => 'agree-cdn-tos float-right', 'type' => 'button', 'disabled' => 'disabled'
                =button_tag 'Cancel', 'class' => 'float-right mr-1', 'data-dismiss' => 'modal', 'type' => 'button'