config/routes.rb
        get :change_state
        get :refund_merchant
        match :update_invoice, via: %i[put post]
        match :transfer_order, via: %i[put post]
        match :update_tags, via: %i[put post]
      end
    end
    resources :billing_profiles

    resource :ssl_account do
      get :edit_settings
      get :validate_ssl_slug
      match :update_settings, via: %i[put patch]
      match :update_ssl_slug, via: %i[put patch]
      match :update_company_name, via: %i[put patch]
      collection do
        post :register_duo
        put  :duo_enable
        put  :duo_own_used
        put  :set_2fa_type
        post :remove_reseller
        post :manage_reseller
      end
      member do
        get :adjust_funds
      end
    end

    resources :users, only: :index do
      match :enable_disable, via: %i[put patch], on: :member
      match :enable_disable_duo, via: %i[put patch], on: :member
    end

    resources :api_credentials do
      member do
        patch 'update_roles'
        get   'remove'
      end
    end

    resource :api_credential do
      collection do
        post :reset_credential
      end
    end

    resource :account, controller: :users do
      resource :reseller
    end

    resources :managed_users, only: %i[new create edit] do
      member do
        patch 'update_roles'
        get   'remove_from_account'
      end
    end

    resources :cdns do
      post :register_account, on: :collection
      # post :register_api_key, on: :collection
      delete :delete_resources, on: :collection
      get :check_cname, on: :collection

      member do
        get :resource_cdn
        patch :update_resource
        post :add_custom_domain
        post :update_custom_domain
        post :update_advanced_setting
        delete :delete_resource
        delete :purge_cache
        post :update_cache_expiry
      end
    end

    get '/orders/filter_by_state/:id' => 'orders#filter_by_state', as: :filter_by_state_orders
    match '/validation_histories/:id/documents/:style.:extension' => 'validation_histories#documents', :as => :validation_document, style: /.+/i, via: %i[get post]
    get 'certificate_orders/filter_by/:id' => 'certificate_orders#filter_by', as: :filter_by_certificate_orders
    get 'certificate_orders/filter_by_scope/:id' => 'certificate_orders#filter_by_scope', as: :filter_by_scope_certificate_orders
    match 'get_free_ssl' => 'funded_accounts#create_free_ssl', :as => :create_free_ssl, via: %i[get post]
    match 'secure/allocate_funds' => 'funded_accounts#allocate_funds', :as => :allocate_funds, via: %i[get post]
    match 'secure/allocate_funds_for_order/:id' => 'funded_accounts#allocate_funds_for_order', :as => :allocate_funds_for_order, via: %i[get post]
    match 'secure/deposit_funds' => 'funded_accounts#deposit_funds', :as => :deposit_funds, via: %i[get put patch post]
    match 'secure/confirm_funds/:id' => 'funded_accounts#confirm_funds', :as => :confirm_funds, via: %i[get post]
    match 'secure/apply_funds' => 'funded_accounts#apply_funds', :as => :apply_funds, via: %i[get post put]
    match 'users/new/affiliates' => 'users#new', :as => :affiliate_signup, via: %i[get post]
    match 'affiliates/:affiliate_id/orders' => 'orders#affiliate_orders', :as => :affiliate_orders, via: %i[get post]
    match ':user_id/orders' => 'orders#user_orders', :as => :user_orders, via: %i[get post]

    match 'paypal_express/checkout', via: %i[get post]
    match 'paypal_express/review', via: %i[get post]
    match 'paypal_express/purchase', via: %i[get post]

    match "/site_seals/:id/site_report'," => 'site_seals#site_report', via: :get

    # mailbox
    get 'mail/inbox' => 'mailbox#inbox', as: :mail_inbox
    get 'mail/sent' => 'mailbox#sent', as: :mail_sent
    get 'mail/trash' => 'mailbox#trash', as: :mail_trash
    match 'mail/compose' => 'mailbox#compose', as: :mail_compose, via: %i[get post]
    get 'mail/read' => 'mailbox#read', as: :mail_read
    put 'mail/reply' => 'mailbox#reply', as: :mail_reply
    put 'mail/move_to_trash' => 'mailbox#move_to_trash', as: :mail_move_to_trash
  end

  scope '(/team/:ssl_slug)', module: false do
    concerns :teamable
  end

  # User verifications, eg OTP
  resources :verifications
  resources :otps do
    collection do
      get :email
      get :email_login
      get :login
      post :verify_login
      get :add_phone
      post :verify_add_phone
    end
  end

  resources :u2fs do
    collection do
      post :verify
    end
  end

  resources :users, except: :index do
    collection do
      get :edit_password
      get :edit_email
      match :resend_activation, via: %i[get post]
      get :activation_notice
      get :search
      get :cancel_reseller_signup
      match :enable_disable, via: %i[put patch]
      match :enable_disable_duo, via: %i[put patch]
      get :show_user
      get :reset_failed_login_count
      match :upload_avatar, format: /(js|json)/, via: %i[put patch]
      get :avatar, format: /(js|json)/
    end

    member do
      get   :edit_password
      get   :edit_email
      get   :login_as
      match :admin_update, via: %i[put patch]
      get   :admin_show
      get   :dup_info
      post  :consolidate
      get   :adjust_funds
      get   :change_login
      get   :switch_default_ssl_account
      get   :approve_account_invite
      get   :resend_account_invite
      get   :decline_account_invite
      get   :teams
      get   :search_teams
      match :create_team, via: %i[get post]
      put   :set_default_team
      match :set_default_team_max, via: %i[put patch]
      match :admin_activate, via: %i[put patch]
      get   :leave_team
      get   :dont_show_again
      get   :duo
      match :duo_verify, via: %i[get post]
      get   :archive_team
      get   :retrieve_team
    end
  end

  resources :apis
  match '/certificates/pricing', to: 'certificates#pricing', as: :certificate_pricing, via: %i[get post]
  resources :certificates do
    collection do
      get :single_domain
      get :wildcard_or_ucc
      get :admin_index
    end
    member do
      get :buy
      get :buy_renewal
      match :manage_product_variants, via: %i[get post]
    end
  end

  scope '(/team/:ssl_slug)' do
    resources :phone_callbacks, only: [:create] do
      get 'approvals', on: :collection
      get 'verifications', on: :collection
    end
  end

  match '/contacts/:id/admin_update' => 'contacts#admin_update', as: :admin_update_contact, via: %i[put post]
  match '/ssl_manager/:id/approve' => 'registered_agents#approve', :as => :approve_ssl_manager, via: [:get]
  match '/activate/:id' => 'activations#create', :as => :activate, via: %i[get post]
  match '/register/:activation_code' => 'activations#new', :as => :register, via: %i[get post]
  match '/sitemap.xml' => 'site#sitemap', :as => :sitemap, via: %i[get post]
  match 'reseller' => 'site#reseller', :as => :reseller, :constraints => { subdomain: Reseller::SUBDOMAIN }, via: %i[get post]
  match '/subject_alternative_name' => 'site#subject_alternative_name', as: :san, via: %i[get post]
  match 'browser_compatibility' => 'site#compatibility', as: :browsers, via: %i[get post]
  match 'acceptable-top-level-domains-tlds-for-ssl-certificates' => 'site#top_level_domains_tlds', as: :tlds, via: %i[get post]
  match '/certificate_order_token/:token/generate_cert' => 'certificate_orders#generate_cert', :as => :confirm, via: [:get]
  match '/download_certificates/:co_ids' => 'certificate_orders#download_certificates', as: :download_certificates, via: [:post], defaults: { format: :csv }
  match '/validation/email_verification_check' => 'validations#email_verification_check', :as => :email_verification_check, via: [:post]

  # Callback
  match '/callback/:token' => 'validations#verification', :as => :email_verification, via: [:get]
  match '/validation/automated_call' => 'validations#automated_call', :as => :automated_call, via: [:post]
  match '/validation/phone_verification_check' => 'validations#phone_verification_check', :as => :phone_verification_check, via: [:post]
  match '/validation/register_callback' => 'validations#register_callback', :as => :register_callback, via: [:post]

  # Test Attestation
  match '/verify-attestation' => 'attestation_certificates#verify_attestation', :as => :verify_attestation, via: [:get]
  match '/check-attestation-verification' => 'attestation_certificates#check_attestation_verification', :as => :check_attestation_verification, via: [:post]

  # match 'paid_cert_orders'=> 'site#paid_cert_orders'
  (Reseller::TARGETED + SiteController::STANDARD_PAGES).each do |i|
    send('get', i => "site##{i}", :as => i.to_sym)
  end
  match 'certificates/apidocs/apply' => 'restful_api#docs_apply_v1_3', :as => :restful_apidocs_apply, via: %i[get post]
  match 'certificates/apidocs/dcv' => 'restful_api#dcv', :as => :restful_api_dcv, via: %i[get post]

  # took the anchor version out /\w+\/?\z/ but need to test the results of this,
  # specifically the aff code should be the last thing and not followed by other characters
  # that could route this to anything other than an affiliate crediting
  get '*disregard/code/:id' => 'affiliates#refer', id: %r{\w+/?}
  get '/code/:id' => 'affiliates#refer', id: %r{\w+/?}

  resources :surls, constraints: { subdomain: Surl::SUBDOMAIN }, except: %i[index show]
  get '/surls/:id' => 'surls#destroy', :constraints => { subdomain: Surl::SUBDOMAIN }
  get '/surls/status_204' => 'surls#status_204', :constraints => { subdomain: Surl::SUBDOMAIN }
  post '/surls/login/:id' => 'surls#login', as: :surl_login, :constraints => { subdomain: Surl::SUBDOMAIN }
  get '/ssl_links_disclaimer' => 'surls#disclaimer', as: :ssl_links_disclaimer, :constraints => { subdomain: Surl::SUBDOMAIN }
  # get ':id'=>'surls#show', id: /[0-9a-z]+/i
  match '/:controller(/:action(/:id))', via: %i[get post]
  # match "*path" => redirect("/?utm_source=any&utm_medium=any&utm_campaign=404_error")

app/models/u2f.rb
class U2f < ApplicationRecord
  belongs_to :user

  validates :nick_name, :key_handle, presence: true
end

app/controllers/u2fs_controller.rb
# frozen_string_literal: true

class U2fsController < ApplicationController
  before_action :current_user
  before_action :require_user, except: %i[new verify]
  skip_before_action :use_2fa_authentication
  skip_before_action :verify_u2f_authentication, only: %i[new verify]

  def index
    @u2fs = current_user.u2fs
    key_handles = current_user.u2fs.pluck(:key_handle)

    # Prepare what we need to add a new key to user account
    @app_id = u2f.app_id
    @registration_requests = u2f.registration_requests
    @sign_requests = u2f.authentication_requests(key_handles)
    # Store challenges. We need them for the verification step
    session[:challenges] = @registration_requests.map(&:challenge)

    redirect_to verifications_path unless current_user.authy_user && current_user.phone && current_user.phone_prefix
  end

  def new
    redirect_to user_account_path if session[:authenticated]
    @u2f_info = {}
    key_handles = current_user.u2fs.pluck(:key_handle)

    u2f = U2F::U2F.new(request.base_url)
    unless key_handles.empty?
      # Generate SignRequests
      @app_id = u2f.app_id
      @sign_requests = u2f.authentication_requests(key_handles)

      session[:challenge] = u2f.challenge
    end
    session[:u2f_failed_count] ||= 0
  end

  def verify
    @user ||= current_user || User.find_by(id: session[:pre_authenticated_user_id])
    redirect_to login_path and return unless @user

    # No need for verification if user does not have any keys
    return true unless @user.u2fs.any?

    # If user has keys, we need to have a u2f_response, so that we can validate it!
    return false if params['u2f_response'].blank?

    if params[:error_message].present? || JSON.parse(params[:u2f_response])['errorCode'].present?
      flash[:error] = params[:error_message]
      session[:u2f_failed_count] += 1
      u2f_timeout = true if JSON.parse(params[:u2f_response])['errorCode'] == 5

      redirect_to logout_path and return if u2f_timeout || session[:u2f_failed_count] >= 3
      redirect_to new_u2f_path and return
    end

    @result_obj = params[:result_object]
    response = U2F::SignResponse.load_from_json(params[:u2f_response]) if params[:u2f_response].present?
    u2f_registration = @user.u2fs.find_by(key_handle: response.key_handle) if response&.key_handle

    begin
      u2f.authenticate!(
        session[:challenge],
        response,
        Base64.decode64(u2f_registration.public_key),
        u2f_registration.counter
      )

      u2f_registration.update(counter: response.counter)

      session[:authenticated] = true
      respond_to do |format|
        format.html {
          # Check if user has verifications
          if  current_user.authy_user && current_user.phone && current_user.phone_prefix
            set_redirect(user: @user)
          else
            redirect_to verifications_path and return
          end
        }
      end
    rescue U2F::Error => e
      flash[:error] = 'Unable to authenticate with U2F: ' + e.class.name # unless params[:user]
      session[:u2f_failed_count] += 1

      redirect_to new_u2f_path
    ensure
      session.delete(:challenge)
    end
    session[:u2f_failed_count] = 0

  end

  def create
    if params[:u2f_response].blank?
      flash[:error] = 'Could not add key'
      redirect_to u2fs_path and return
    end
    response = {}
    u2f_response = U2F::RegisterResponse.load_from_json(params[:u2f_response])

    exist = current_user.u2fs.find_by(key_handle: u2f_response.key_handle)
    if exist
      @error = 'This U2F device has already been registered.'
      response['error'] = 'This U2F device has already been registered.'
    end

    begin
      u2f_registration = u2f.register!(session[:challenges], u2f_response)

      current_user.u2fs.create!(nick_name:   params['nick_name'],
                                certificate: u2f_registration.certificate,
                                key_handle:  u2f_registration.key_handle,
                                public_key:  u2f_registration.public_key,
                                counter:     u2f_registration.counter)
    rescue U2F::Error => e
      response['error'] = 'Unable to register: ' + e.class.name
    ensure
      session.delete(:challenges)
    end
    @u2fs = current_user.u2fs

    render json: response
  end

  def update
    @u2f = current_user.u2fs.find_by(id: params[:id])
    if @u2f.update(u2f_params)
      flash.now[:notice] = 'Successfully updated'
    else
      flash.now[:warning] = 'Could not update'
    end

    render json: { result: 'success', u2f_description: u2f.nick_name }
  end

  def destroy
    redirect_to root_path and return unless current_user
    response = {}
    u2f = current_user.u2fs.find_by(id: params['id'])
    if u2f
      u2f.destroy
      response['u2f_device_id'] = u2f.id
    else
      response['error'] = 'There is no data for selected U2f Token'
    end

    render json: response
  end
end

private

def u2f_params
  params.require(:u2f).permit(:nick_name)
end

app/views/u2fs/_add_key.html.haml
.u2f_block.add_nick_name.hidden
  = form_for U2f.new, remote: true do |f|
    = text_field_tag 'u2f_device_name', nil, size: 30, class: 'left u2f_device_name', placeholder: 'Enter a nickname for this security key.'
    = button_tag 'Add', type: 'button', class: 'add_u2f_device disabled'

  .u2f_error_message
-# This will show a dialog window informing the user to touch the security key
#loading
.u2f_block.register
  .clearfix
  = button_tag 'Register New Device', type: 'button', class: 'register_u2f', disabled: !current_user.authy_user, title: "#{'Please verify your phone!' unless current_user.authy_user }", id: 'u2f-new'
  - unless current_user.authy_user && current_user.phone && current_user.phone_prefix
    %br
      %i Required: If you lose your security key, we will send you a code via email or SMS

.clearfix#2fa-info{ style: 'display: none;' }
  = render partial: 'shared/u2f_waiting_bar'

app/views/u2fs/_form.html.haml
.clearfix
.u2f_block#waiting_bar
  = image_tag('waiting_bar_medium.gif', style: 'vertical-align: middle;')
  #waiting_bar_text
    Insert your key and touch it
= link_to 'Or request a code via SMS', '#'

app/views/u2fs/_index_scripts.html.erb
<script type="text/javascript">
jQuery.noConflict();
jQuery(function($) {
  $(document).ready(function() {
    var appId = <%= @app_id.to_json.html_safe %>
    var signRequests = <%= @sign_requests.as_json.to_json.html_safe %>;
    var registerRequests = <%= @registration_requests.to_json.html_safe  %>;
    var u2f_error_message_element = $('.u2f_error_message');

    var authenticated_session = <%= session[:authenticated] %>;

    // Yubikey error codes for register
    var errorMap_register = {
      1: 'Unknown error, please try again or contact us',
      2: "Bad request error, try again" ,
      3: "This key isn't supported, please try another one",
      4: 'The device is already registered.',
      5: 'Authentication timed out. Please reload to try again.'
    };

    // Yubikey error codes for sign
    var errorMap_sign = {
      1: 'Unknown error, please try again or contact us',
      2: "Bad request error, try again" ,
      3: "This key isn't supported, please try another one",
      4: 'Could not authenticate you. Please try again.',
      5: 'Authentication timed out. Please try again.'
    };

    // We are here because our login requires 2FA
    // as long as the session is not authenticated yet
    // Authenticate with key
    if (!authenticated_session) {
      var challenge = <%= session[:challenge].to_json.html_safe %>;
      $('#2fa-info').show();

      var setError = function(code) {
        //$waiting.style.display = 'none';
        //$error.style.display = 'block';
        //$error.innerHTML = errorMap[code];
        $('#error_message').val(errorMap_sign[code])
        var failed_count = parseInt($('.failed_count').val()) + 1;
        $('.failed_count').val(failed_count);
        $('.u2f_logout').val('true');
      };

      u2f.sign(appId, challenge, signRequests, function(signResponse) {
        if (signResponse.errorCode) {
          $('#2fa-info').hide();
          setError(signResponse.errorCode);
        }
        $('.u2f_response').val(JSON.stringify(signResponse));
        $('#verify-u2f').submit();
      }, 60);
    }

    // Add key
    $('.register_u2f').click(function() {
      $('.u2f_block.register').hide();
      $('.u2f_device_name').val('');
      $('.add_u2f_device').prop('disabled', true);
      $('.u2f_block.add_nick_name').show();
      $('#u2f_device_name').focus();
    });

    $('.u2f_device_name').keyup(function() {
      if ($(this).val().trim() == '') {
        $('.add_u2f_device').prop('disabled', true);
      } else {
        $('.add_u2f_device').prop('disabled', false);
      }
    });

    // Edit key description
    $(document).on('click', 'button[class*="edit_u2f_device"]', function() {
      id = $(this).data('id')
      $('.u2f_device_info_block#u2f_device_' + id + ' #u2f_description').hide();
      $('.u2f_device_info_block#u2f_device_' + id + ' #u2f_edit').removeClass('hidden');
      $('.u2f_device_info_block#u2f_device_' + id + ' #u2f_edit input').focus();
    });

    // Remove key
    var ajaxRemoveU2fUrl = '/u2fs'; //u2fs#destroy
    $(document).on('click', 'button[class*="remove_u2f_device"]', function() {
      if (confirm('Are you sure to remove this token?')) {
        var registerRequests = <%= @registration_requests.to_json.html_safe  %>;

        $.ajax({
          url: "/u2fs/"+$(this).data('id'),
          type: 'DELETE',
          success: function (result) {
            if (result['error']) {
              if (result['error'] == '') {
                location.reload(true);
              } else {
                var message_wrap_element = $('<div></div>');
                message_wrap_element.attr('class', 'flash_message error');

                var message_element = $('<span></span>');
                message_element.append(result['error']);
                message_wrap_element.append(message_element);

                var btn_element = $('<small></small>');
                var close_btn_element = $('<div></div>');
                close_btn_element.attr('class', 'close_flash_message');

                var close_sign_element = $('<span></span>');
                close_sign_element.append('X');

                close_btn_element.append(close_sign_element);
                close_btn_element.append('close');

                btn_element.append(close_btn_element);
                message_wrap_element.append(btn_element);

                if ($('#content').find('.inner').children().first().hasClass('flash_message')) {
                  $('#content').find('.inner').children().first().remove();
                }
                message_wrap_element.insertBefore($('#content').find('.inner').children().first());
              }
            } else {
              location.reload(true);
            }
          }
        });
      }
    });

    var ajaxRegisterU2fUrl = '<%= u2fs_path %>'; // u2fs#create
    $('.add_u2f_device').click(function(event) {
      u2f_error_message_element.hide();
      $('#2fa-info').show();
      u2f.register(appId, registerRequests, signRequests, function(registerResponse) {
        if (registerResponse.errorCode) {
          u2f_error_message_element.show();
          u2f_error_message_element.text(errorMap_register[registerResponse.errorCode]);
          u2f_error_message_element.css('color', 'red');
          $('#2fa-info').hide();
        } else {
          $.ajax({
            url: ajaxRegisterU2fUrl,
            data: {
              nick_name: $('.u2f_device_name').val(),
              u2f_response: JSON.stringify(registerResponse)
            },
            type: 'POST',
            success: function(result) {
              if (result['error']) {
                if (result['error'] == '') {
                  location.reload(true);
                } else {
                  var message_wrap_element = $('<div></div>');
                  message_wrap_element.attr('class', 'flash_message error');

                  var message_element = $('<span></span>');
                  message_element.append(result['error']);
                  message_wrap_element.append(message_element);

                  var btn_element = $('<small></small>');
                  var close_btn_element = $('<div></div>');
                  close_btn_element.attr('class', 'close_flash_message');

                  var close_sign_element = $('<span></span>');
                  close_sign_element.append('X');

                  close_btn_element.append(close_sign_element);
                  close_btn_element.append('close');

                  btn_element.append(close_btn_element);
                  message_wrap_element.append(btn_element);
                  if ($('#content').find('.inner').children().first().hasClass('flash_message')) {
                    $('#content').find('.inner').children().first().remove();
                  }
                  message_wrap_element.insertBefore($('#content').find('.inner').children().first());
                }
              } else {
                location.reload(true);
              }
            }
          });
        }
      });
    });

    $('[id^=submit]').click(function(event){
      url = $(this).data('url')
      id = $(this).data('id')

      $.ajax({
        url: url,
        data: {
          u2f: {
            nick_name: $('#u2f_nick_name_' + id).val()
          }
        },
        type: 'PATCH',
        success: function(data) {
          $('.u2f_device_info_block#u2f_device_' + id + ' #u2f_description').show();
          $('.u2f_device_info_block#u2f_device_' + id + ' #u2f_description').text(data['u2f_description']);
          $('.u2f_device_info_block#u2f_device_' + id + ' #u2f_edit').addClass('hidden');
        }
      });
    });
  });
});
</script>

app/views/u2fs/_phone.html.haml
= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/authy-form-helpers/2.3/form.authy.min.css', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/authy-form-helpers/2.3/form.authy.min.js', 'data-turbolinks-track': 'reload'

.container
  .row
    .col-md-8.offset-md-2
      - selected_country = ISO3166::Country.find_country_by_country_code(current_user&.phone_prefix) || ISO3166::Country.find_country_by_alpha2('US')
      %h4.text-center
        If you lose your security key, we will send you a code via email or SMS
  .row
    .col-md-6.offset-md-3
      = form_for 'user' do |f|
        .input-group
          = select_tag "authy-countries", nil, name: 'country_code', 'data-show-as': 'number', 'data-value': selected_country.country_code
          = f.text_field :phone, value: current_user.phone, autofocus: true, disabled: current_user.phone.present?
          = link_to "enablePhoneEdit()", class: 'btn btn-default' do
            .fa.fa-edit

        %span.clearfix#phone-hint
          We will send you a code via SMS on this number
        %span.clearfix
          #phone-error
      #send-otp
        %br
        = button_tag current_user.phone_verified? ? 'Save' : 'Save and Confirm number', id: 'submit_phone_verification', class: 'btn btn-secondary btn-lg'

        %span{ style: 'vertical-align: middle' }= link_to 'Or send via email', email_otps_path, id: 'otp-email', remote: true, class: 'h4'

      .hidden#code-verification-fields
        = text_field_tag 'otp_verification_code', nil, class: "form-control", autofocus: true
        %span Enter verification code from SMS
        %span.clearfix
          #code-error
        = link_to 'Resend code to phone', '#', id: 'resend-otp-phone'
        %br
        = link_to 'Resend code to email', '#', id: 'resend-otp-email'
        = hidden_field_tag 'otp_authy_user', @authy_user
        .clearfix
        = button_tag "Verify Code", id: 'code_submit'

app/views/u2fs/_twofa_authentication.html.haml
.clearfix
.u2f_block#waiting_bar
  = image_tag('waiting_bar_medium.gif', style: 'vertical-align: middle;')
  #waiting_bar_text
    Insert your key and touch it
#otp-request{ style: 'display: none' }
  .u2f_device_info
    .input-group
      = text_field_tag 'u2f[nick_name]', 'ad', class: 'form-control'
      .input-group-append
        .btn.btn-success.fa.fa-check

app/views/u2fs/index.html.haml
= javascript_include_tag '//stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js'
= stylesheet_link_tag 'bootstrap_style', media: 'all'
= stylesheet_link_tag 'bootstrap_fix'

- @title = "Hardware Tokens"
- content_for :title, @title
= render partial: 'index_scripts'
= javascript_include_tag 'u2f-api'

.container
  .row
    .col-md-8.offset-md-2
      %h3
        Hardware Tokens
      #stylized.default_form
        .u2f_settings
          .settings_block
            .u2f_block.u2f_info
              - if @u2fs.size > 0
                - @u2fs.each do |u2f|
                  .u2f_device_info_block.clearfix{ id: "u2f_device_#{u2f.id}" }
                    .u2f_device_info#u2f_description
                      = u2f.nick_name
                      %span#u2f_description_hint
                    .hidden#u2f_edit
                      = text_field_tag :nick_name, u2f.nick_name, { id: "u2f_nick_name_#{u2f.id}" }
                      %button.btn.btn-success.fa.fa-check{ id: "submit_#{u2f.id}", 'data-url': u2f_path(u2f.id), 'data-id': u2f.id }
                    .u2f_device_info
                      %span - registered on
                      = u2f.created_at.strftime("%b %d, %Y")
                    .u2f_device_info.right
                      = button_tag 'Edit', type: 'button', class: 'edit_u2f_device', 'data-id': u2f.id
                      = button_tag 'Remove', :type=>'button', :class=>'remove_u2f_device', 'data-id'=>u2f.id

            = render partial: 'add_key'

app/views/u2fs/new.html.haml
-title = request.subdomain==Reseller::SUBDOMAIN ? "Reseller login" : "Customer login"
-content_for :title, title
= render partial: 'index_scripts'
= javascript_include_tag 'u2f-api'
-failed_count = @failed_count || 0
-limited_count = Settings.captcha_threshold
.reseller_registration_profile
  = form_for 'u2f', url: verify_u2fs_path, method: :post, html: { id: 'verify-u2f' } do |f|
    %h3=title
    %p
      Login to your #{community_name} account to manage your SSL products and services including certificates,
      links, and monitoring and scanning apps. If you currently do not have an account,
      #{link_to "register for a free #{community_name} account", new_user_url}.
    #stylized.default_form
      .subheading Credentials
      .clearfix.form_input#2fa-info{ style: 'display: none;' }
        = render partial: 'twofa_authentication'
      = hidden_field_tag 'u2f_response', '', :class => 'u2f_response'
      = hidden_field_tag 'failed_count', failed_count, class: 'failed_count'
      = hidden_field_tag 'error_message'

      #forgot_container
        %p#forgot_username_or_password
          Send code to phone?
          = link_to 'Send SMS', login_otps_path
        %p#forgot_username_or_password
          Send code to email?
          = link_to 'Send email', email_login_otps_path
        %p#forgot_username_or_password
          Use DUO?
          = link_to 'DUO authentication', duo_user_session_path