config/routes.rb
# frozen_string_literal: true

require 'domain_constraint'

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api' if defined?(Rswag)
  mount Delayed::Web::Engine, at: '/jobs', constraints: AdminConstraint.new
  mount LetterOpenerWeb::Engine, at: '/letter_opener' unless Rails.env.production?
  mount RegistrationAuthority::Engine, at: '/registration-authority'
  mount Yabeda::Prometheus::Exporter, at: '/metrics', constraints: ServiceConstraint.new

  resources :apidocs, only: [:index]

  match '/' => 'resellers#index', :constraints => { subdomain: Reseller::SUBDOMAIN }, as: 'resellers_root', via: %i[get post]
  match '/' => 'site#index', :as => :root, via: %i[get post]
  match 'login' => 'user_sessions#new', :as => :login, via: %i[get post]
  match 'logout' => 'user_sessions#destroy', :as => :logout, via: %i[get post]
  match '(/team/:ssl_slug)/signed_certificates/:id/revoke' => 'signed_certificates#revoke', as: 'revoke_signed_certificate', via: %i[put post]

  resources :unsubscribes, only: %i[edit update]
  # resources :site_checks
  match 'site_check' => 'site_checks#new', :as => :site_check, via: %i[get post]
  match 'site_checks' => 'site_checks#create', :as => :site_checks, via: %i[get post]
  match 'enterprise_pki_service_agreement' => 'contacts#enterprise_pki_service_agreement', via: :get

  # api: If version is not specified then use the default version in APIConstraint
  constraints DomainConstraint.new((%w[sws-qa.int.ssl.com sws.sslpki.com sws.sslpki.local] + Website.domain_contraints).uniq) do
    scope module: :api do
      scope module: :v1, constraints: APIConstraint.new(version: 1), defaults: { format: 'json' } do
        # Users
        match '/users' => 'api_user_requests#create_v1_4', as: :api_user_create_v1_4, via: %i[options post]
        match '/user/:login' => 'api_user_requests#show_v1_4', as: :api_user_show_v1_4, via: %i[options get], login: %r{.+/?}
        match '/users/get_teams' => 'api_user_requests#get_teams_v1_4', as: :api_user_get_teams_v1_4, via: %i[options get], get_teams: %r{.+/?}
        match '/users/set_default_team' => 'api_user_requests#set_default_team_v1_4', as: :api_user_set_default_team_v1_4, via: %i[options put], set_default_team: %r{.+/?}

        # SSL Manager
        match '/ssl_manager' => 'api_ssl_manager_requests#register', as: :api_ssl_manager_register, via: %i[options post]
        match '/ssl_manager/collection' => 'api_ssl_manager_requests#collection', as: :api_ssl_manager_collection, via: %i[options post]
        match '/ssl_managers' => 'api_ssl_manager_requests#delete', as: :api_ssl_managers_delete, via: %i[options delete]
        match '/ssl_managers' => 'api_ssl_manager_requests#index', as: :api_ssl_managers_index, via: %i[options get]
        match '/ssl_manager/collections' => 'api_ssl_manager_requests#collections', as: :api_ssl_managers_collections, via: %i[options get]

        # ACME
        match '/acme/hmac' => 'api_acme_requests#retrieve_hmac', as: :api_acme_retrieve_hmac, via: [:post]
        match '/acme/credentials' => 'api_acme_requests#retrieve_credentials', as: :api_acme_retrieve_credentials, via: [:post]
        match '/acme/validations/info' => 'api_acme_requests#validations_info', as: :api_acme_validations_info, via: [:post]
        match '/acme/:certificate_order_ref/domain/validation/status' => 'api_acme_requests#validation_status', as: :api_acme_domain_validation_status, via: [:post]

        # Code Signing.
        match '/generate_certificate' => 'api_certificate_requests#generate_certificate_v1_4', as: :api_certificate_generate_v1_4, via: %i[options post]

        # Teams
        match '/teams/add_contact' => 'teams#add_contact', as: :api_team_add_contact, via: :post
        match '/teams/add_registrant' => 'teams#add_registrant', as: :api_team_add_registrant, via: :post
        match '/teams/add_billing_profile' => 'teams#add_billing_profile', as: :api_team_add_billing_profile, via: :post
        match '/teams/saved_contacts' => 'teams#saved_contacts', as: :api_team_saved_contacts, via: :get
        match '/teams/saved_registrants' => 'teams#saved_registrants', as: :api_team_saved_registrants, via: :get
        match '/teams/user' => 'teams#show_user', as: :api_team_user, via: :get
        match '/teams/verify_user_by_id' => 'teams#verify_user_by_id', as: :api_team_verify_user_by_id, via: %i[get post]
        match '/team' => 'teams#show_team', as: :api_team_team, via: :get

        # Signed Certificates
        match '/signed_certificates' => 'api_certificate_requests#retrieve_signed_certificates', as: :api_signed_certificates_retrieve, via: [:post]

        # Certificate Enrollment
        match '/certificate_enrollment' => 'api_certificate_requests#certificate_enrollment_order', as: :api_certificate_enrollment, via: :post

        # Certificates
        match '/certificates' => 'api_certificate_requests#create_v1_4', as: :api_certificate_create_v1_4, via: [:post]
        match '/certificate/:ref' => 'api_certificate_requests#update_v1_4', as: :api_certificate_update_v1_4, via: %i[options put patch post], ref: /[a-z0-9\-]+/
        match '/certificate/:ref/replace' => 'api_certificate_requests#replace_v1_4', as: :api_certificate_replace_v1_4, via: %i[options put patch post], ref: /[a-z0-9\-]+/
        match '/certificate/:ref' => 'api_certificate_requests#show_v1_4', as: :api_certificate_show_v1_4, via: %i[options get], ref: /[a-z0-9\-]+/
        match '/certificate/:ref/callback' => 'api_certificate_requests#callback_v1_4', as: :api_certificate_callback_v1_4, via: %i[options put patch post], ref: /[a-z0-9\-]+/

        match '/certificate/:ref/contacts' => 'api_certificate_requests#contacts_v1_4', as: :api_certificate_contacts_v1_4, via: %i[options put patch post], ref: /[a-z0-9\-]+/

        match '/certificate/:ref/detail' => 'api_certificate_requests#detail_v1_4', as: :api_certificate_detail_v1_4, via: %i[options get], ref: /[a-z0-9\-]+/
        match '/certificate/:ref/detail/site_seal' => 'api_certificate_requests#update_site_seal_v1_4', as: :api_certificate_update_site_seal_v1_4, via: %i[options post], ref: /[a-z0-9\-]+/
        match '/certificate/:ref/validation/document_upload' => 'api_certificate_requests#view_upload_v1_4', as: :api_certificate_view_upload_v1_4, via: %i[options get], ref: /[a-z0-9\-]+/
        match '/certificate/:ref/validation/document_upload' => 'api_certificate_requests#upload_v1_4', as: :api_certificate_upload_v1_4, via: %i[options post], ref: /[a-z0-9\-]+/

        match '/certificate/:ref' => 'api_certificate_requests#revoke_v1_4', as: :api_certificate_revoke_v1_4, via: %i[options delete]
        match '/certificates' => 'api_certificate_requests#index_v1_4', as: :api_certificate_index_v1_4, via: [:get]
        match '/certificates/validations/email' => 'api_certificate_requests#dcv_emails_v1_3', as: :api_dcv_emails_v1_4, via: %i[options get]
        match '/certificate/:ref/validations/methods' => 'api_certificate_requests#dcv_methods_v1_4', as: :api_dcv_methods_v1_4, via: %i[options get]
        match '/certificate/:ref/pretest' => 'api_certificate_requests#pretest_v1_4', as: :pretest_v1_4, via: %i[options get]
        match '/certificate/:ref/api_parameters/:api_call' => 'api_certificate_requests#api_parameters_v1_4', as: :api_parameters_v1_4, via: %i[options get]
        match '/certificate/:ref/retry_domain_validation' => 'api_certificate_requests#api_resend_domain_validation_v1_4', as: :api_resend_domain_validation_v1_4, via: %i[options post]
        match '/scan/:url' => 'api_certificate_requests#scan', as: :api_scan, via: %i[options get], constraints: { url: %r{[^/]+} }
        match '/analyze/:url' => 'api_certificate_requests#analyze', as: :api_analyze, via: %i[options get], constraints: { url: %r{[^/]+} }
        match '/certificates/validations/csr_hash' => 'api_certificate_requests#dcv_methods_csr_hash_v1_4', as: :api_dcv_methods_csr_hash_v1_4, via: %i[options post]
        match '/certificates/1.3/retrieve' => 'api_certificate_requests#retrieve_v1_3', as: :api_certificate_retrieve_v1_3, via: %i[options get]
        match '/certificates/1.3/dcv_emails' => 'api_certificate_requests#dcv_emails_v1_3', as: :api_dcv_emails_v1_3, via: %i[options get post]
        match '/certificates/1.3/dcv_email_resend' => 'api_certificate_requests#dcv_email_resend_v1_3', as: :api_dcv_email_resend_v1_3, via: %i[options get]
        match '/certificates/1.3/reprocess' => 'api_certificate_requests#reprocess_v1_3', as: :api_certificate_reprocess_v1_3, via: %i[options get]
      end
    end
  end

  resources :password_resets, except: [:show]

  constraints DomainConstraint.new(%w[reseller.ssl.com reseller.ssl.local]) do
    resources :resellers, only: %i[index new] do
      collection do
        get :details
        get :restful_api
      end
    end
  end

  resources :affiliates do
    collection do
      get :details
    end

    member do
      get :links
      get :sales
    end
  end

  resources :reseller_tiers do
    member do
      get :show_popup
    end
  end

  concern :teamable do
    match '/enrollment/:product/:duration' => 'certificate_enrollment_requests#new', as: 'new_certificate_enrollment_request', via: %i[get post], duration: %r{\d+/?}
    match '/enrollment_links' => 'certificate_enrollment_requests#enrollment_links', as: 'enrollment_links_certificate_enrollment_requests', via: :get

    resources :folders, only: %i[index create update destroy] do
      collection do
        put :reset_to_system
        get :children
      end
      member do
        put :add_certificate_order
        put :add_certificate_orders
      end
    end

    resources :certificate_enrollment_requests, except: %i[edit new update show] do
      member do
        match :reject, via: %i[put post]
      end
    end

    resources :domains, only: %i[index create update destroy] do
      collection do
        match :validate_all, via: %i[get post]

app/models/concerns/certificate/x509_properties.rb
module Concerns
  module Certificate
    module X509Properties
      extend ActiveSupport::Concern

      def openssl_x509
        OpenSSL::X509::Certificate.new(body.strip)
      end

      def issuer_dn
        openssl_x509.issuer.to_utf8
      end

      def dn
        openssl_x509.subject.to_s
      end

      def not_after
        openssl_x509.not_after
      end

    end
  end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
  def certificate_crumbs
    crumb = link_to 'ssl certificates', certificates_path
    crumb << ' :: '
    crumb << if @certificate.is_ucc? || @certificate.is_wildcard?
               link_to('wildcard or ucc', wildcard_or_ucc_certificates_url)
             else
               link_to('single domain', single_domain_certificates_url)
             end
    crumb << " :: #{@certificate.title}"
  end

  def new_certificate_params
    if @certificate_order.is_unused_credit?
      [@certificate_order, { url: :update_csr_certificate_order }]
    elsif current_user&.ssl_account&.is_registered_reseller?
      @certificate_order
    else
      [@certificate_order, { url: :new_order }]
    end
  end

  def buy_or_get
    @certificate.is_free? ? 'Get' : 'Buy'
  end

  def pricing(certificate)
    last_duration_pricing certificate
  end

  def last_duration_pricing(certificate)
    years = certificate.last_duration.value.to_i / 365
    years = 1 unless years > 0
    p = lambda do |cert|
      if cert.is_ucc?
        cert.first_domains_tiers.last.price * 3
      else
        cert.last_duration.price
      end
    end
    price = p.call(certificate)
    orig_price = p.call(certificate.untiered)
    actual = (price / years).format
    unless certificate.is_dv?
      orig = (certificate.tiered? ?
       (orig_price / years).format : nil)
    end
    render partial: 'pricing', locals: { actual: actual, orig: orig }
  end

  def first_duration_pricing
    actual = certificate.first_duration.price.format
    unless certificate.is_dv?
      orig = (certificate.tiered? ?
       certificate.untiered.first_duration.price.format : nil)
    end
    render partial: 'pricing', locals: { actual: actual, orig: orig }
  end
end

app/views/certificates/_big_pricing.html.haml
-if (current_user && current_user.ssl_account.is_registered_reseller?) || cookies[ResellerTier::TIER_KEY]
  .reseller_price_starting_at as low as #{pricing(@certificate)}
-else
  .price_starting_at as low as #{pricing(@certificate)}/yr

app/views/certificates/_certificate_detail.html.haml
%td(valign='top' height='128')
  %a(href="#{certificate_url :id=>c.product_root}")
    =image_tag(c.icons["main"], :class=> (c.product_root =~ /ev/) ? 'bordered_prod' : '')
%td(valign='top')
  %a(href="#{certificate_url :id=>c.product_root}")
    .summary=c.description['summary']
    .title=c.title
    .starting_at
      -unless c.product_root=='free'
        as low as
      -else
        get for
      #{pricing(c)}/yr
  .more_info
    =link_to image_tag('more_info_sm_bl.gif', :title=>'click to see this certificate'), certificate_url(c.product_root)
    -unless c.product_root=='free'
      =link_to image_tag('buy_sm_bl.gif', :title=>'click to buy this certificate'), buy_certificate_url(c.product_root)
    -else
      =link_to image_tag('get_sm_bl.gif', :title=>'click to get this certificate'), buy_certificate_url(c.product_root)

app/views/certificates/_form_for_admin_pvg_attrs.html.haml
- pv_group = ProductVariantGroup
- title_select = pv_group.pluck(:title).uniq.sort
- status_select = pv_group.pluck(:status).uniq.sort
- desc_select = pv_group.pluck(:description).uniq.sort
- text_desc_select = pv_group.pluck(:text_only_description).uniq.sort
- published_select = pv_group.pluck(:published_as).uniq.sort

- if !pvg.is_a?(ProductVariantGroup) && pvg.object
  .clearfix
    = pvg.label :title
    = pvg.select :title, title_select, include_blank: false

  .clearfix
    = pvg.label :status
    = pvg.select :status, status_select, include_blank: false

  .clearfix
    = pvg.label :description
    = pvg.select :description, desc_select, include_blank: false
    
  .clearfix
    = pvg.label :text_only_description
    = pvg.select :text_only_description, text_desc_select, include_blank: false
    
  .clearfix
    = pvg.label :display_order
    = pvg.number_field :display_order, value: pvg.object.display_order, step: 1

  .clearfix
    = pvg.label :published_as
    = pvg.select :published_as, published_select, include_blank: false

- else
  .clearfix
    = label_tag :title
    = select_tag :title, options_for_select(title_select), include_blank: false

  .clearfix
    = label_tag :status
    = select_tag :status, options_for_select(status_select), include_blank: false

  .clearfix
    = label_tag :description
    = select_tag :description, options_for_select(desc_select), include_blank: false
    
  .clearfix
    = label_tag :text_only_description
    = select_tag :text_only_description, options_for_select(text_desc_select), include_blank: false
    
  .clearfix
    - pvg_list = @certificate.product_variant_groups
    - display_order = pvg_list.any? ? (pvg_list.pluck(:display_order).sort.last + 1) : 1
    = label_tag :display_order
    = number_field_tag :display_order, display_order, step: 1, required: true

  .clearfix
    = label_tag :published_as
    = select_tag :published_as, options_for_select(published_select), include_blank: false

app/views/certificates/_points_and_other_certs.html.haml
.product_detail
  .p_body
    .p_points_container
      .p_points
        =@certificate.description["points"].html_safe unless @certificate.description.blank?
#comes_with_site_seal
  #container
    =image_tag(image_url("ssl_seal_1#{'_ev' if @certificate.is_ev?}.png", false), width: "130px")
    #description
      Each #{@certificate.title} certificate comes with the following #{community_name}
      Secured Smart SeaL logo to be displayed on secured websites.
      =link_to "Click here for details.", details_site_seals_path
.see_other_certificates
  %ul
    %li.heading Other Certificates
    -@certificates.each do |cert|
      -unless cert==@certificate
        %li=link_to cert.title, certificate_path(:id=>cert.product_root)

app/views/certificates/buy_ucc.html.haml
-c={}
-c[:description]="Purchase ssl certificates and digital certificates from ssl.com. Buy ev, wildcard, uc, code signing, or any digital certificate."
-c[:keywords]="buy ssl certificate purchase code signing certificates low cost prices ev wildcard uc ucc exchange apache java iis"
-co=@certificate_order
-if @renewing
  -c[:title] = "Renewing #{@certificate.title} Certificate For #{@renewing.subject}"
-elsif @reprocessing
  -c[:title] = "Reprocessing #{@certificate.title} Certificate For #{co.subject}"
-else
  -c[:title] = "#{co.is_unused_credit? ? "Process" : buy_or_get} #{@certificate.title} Certificate"
-c.each do |k, v|
  -content_for k, c[k]
=order_progress_indicator(1, @certificate)
-form_params=new_certificate_params
#buy_other_certs
  %ul
    %li.heading Other Certificates
    -Certificate.base_products.available.reject{|c|c.product=~/free/}.each do |cert|
      -unless cert==@certificate
        %li=link_to cert.title, buy_certificate_path(:id=>cert.product_root)
.reseller_registration_profile
  #buy_certificate_heading
    %h1
      =c[:title]
      =link_to "(click here for product details)", certificate_url(@certificate)
    %h2 Please fill out the required fields below to begin your certificate order.
  =error_messages_for :certificate_order, :certificate_content
  #stylized.default_form.clearfix
    -if !(Settings.show_csr_submit_on_buy_page || @certificate_order.is_unused_credit?)
      -if @certificate.is_code_signing?
        %p #{@certificate.title} Certificate Summary
        %ul.cert_reqs
          %li Used to secure apps by making them tamper proof
          %li Validates the identity of the owner or author of the application to be installed
          %li Eliminates "Untrusted App" dialogs when installing or executing the application
          %li Prevents unauthorized bundling of app with other applications (such as malware/bloatware/spyware)
      -elsif @certificate.is_wildcard?
        %p #{@certificate.title} Summary
        %ul.cert_reqs
          %li CAN secure any number of subdomains (no limit) for 1 single price
          %li No additional charge for each subdomain
          %li Secures root domain as well as subdomains (ie domain.com, www.domain.com, exch01.domain.com)
          %li All entries will have the same root domain name
          %li CAN use on unlimited ip addresses with multiple, concurrent private keys (great for hosting and virtual hosts)
          %li CAN use certificate on unlimited multiple servers concurrently
        %p Example entries include:
        %ul.cert_reqs
          %li domain.com
          %li www.domain.com
          %li mail.domain.com
          %li lync.domain.com
          %li exch01.domain.com
          %li autodiscover.domain.com
        %p and so on...
      -elsif @certificate.is_premium_ssl?
        %p #{@certificate.title} Summary
        %ul.cert_reqs
          %li CAN secure up to 3 different subdomains
          %li An entry CAN be a Fully Qualified Domain Name (FQDN) or simply a subdomain+domain
          %li All entries MUST have the same domain name, but can have different subdomains; for multi domain ssl please see #{link_to 'UCC SSL', buy_certificate_url("ucc") }
          %li An entry CANNOT represent a wildcard domain name (i.e. *.domain.com); for multi domain wildcard ssl please see #{link_to 'UCC SSL', buy_certificate_url("ucc") }
          %li CAN use on unlimited ip addresses with multiple, concurrent private keys (great for hosting and virtual hosts)
          %li CAN use certificate on unlimited multiple servers concurrently
        %p Example entries include:
        %ul.cert_reqs
          %li www.domain.com
          %li lync.domain.com
          %li any.domain.com
      -elsif @certificate.is_ucc?
        %p #{'Extended Validation' if @certificate.is_ev?} UC Certificate (aka SANs, Exchange SSL, multidomain SSL) Summary
        %ul.cert_reqs
          -if @certificate.is_ev?
            %li Displays your company name with a green background in the address bar
            %li Displays your company details in the SSL Certificate details
          %li CAN secure up to 2000 entries (first 3 non-wildcard are free, additional charge per entry after the 3rd entry)
          %li CAN use certificate on unlimited multiple servers concurrently
          %li CAN change domains at anytime or specify them later without fees or costs
          %li An entry CAN be a Fully Qualified Domain Name (FQDN)
          -unless @certificate.is_ev?
            %li An entry CAN be a single worded server name or an internal ip address (but the certificate #{link_to "will not be effective past Dec 2015", "https://cabforum.org/wp-content/uploads/Guidance-Deprecated-Internal-Names.pdf", target: "_blank"} per CAB Forum Reqs.)
          -unless @certificate.allow_wildcard_ucc?
            %li An entry CANNOT represent a wildcard domain name (i.e. *.domain.com); for multi domain wildcard ssl please see #{link_to 'UCC SSL', buy_certificate_url("ucc") }
          -else
            %li An entry CAN represent a wildcard domain name (i.e. *.domain.com, but NOT multiple levels like *.*.domain.com)
          %li CAN use on unlimited ip addresses with multiple, concurrent private keys (great for hosting and virtual hosts)
        %p Example entries include:
        %ul.cert_reqs
          %li domain.com
          %li www.domain.net
          -unless @certificate.is_ev?
            %li *.example.com
            %li *.apps.domain.co.uk
      -else
        %p
          %em Each domain the ssl certificate will secure conforms to the following:
        %ul.cert_reqs
          -unless @certificate.is_wildcard?
            -unless @certificate.allow_wildcard_ucc?
              %li It CANNOT represent a wildcard domain name (i.e. *.domain.com); for wildcard ssl please see #{link_to 'Wildcard SSL', buy_certificate_url("wildcard") }
            -if @certificate.is_premium_ssl?
              %li It will secure up to 3 subdomain names (i.e. www.domain.com, mail.domain.com, lync.domain.com)
            -else
              %li It will secure a domain name (i.e. domain.com); comes with 'www' subdomain automatically
              %li It will secure a fully-qualified domain name (i.e. mail.domain.com or secure.domain.info, etc)
              -unless @certificate.is_ev?
                -if @certificate.is_ucc?
                  %li It will secure a local ip address (i.e. 10.0.0.0)
                -unless @certificate.is_free?
                  %li It will secure a single word server name (i.e. localhost or bizserver)
              -unless @certificate.is_ucc?
                %li It will secure the 'www' subdomain free of cost
          -else
            %li It will secure all subdomains (i.e. www.domain.com, mail.domain.com, lync.domain.com, etc.)
          %li CAN use certificate on unlimited multiple servers concurrently
          -if @certificate.is_free?
            %li Only documentation support provided, does NOT come with technical support
    =form_for(*form_params) do |f|
      =hidden_field :certificate, :product
      =recert?
      =render :partial => "/certificates/form_ucc", :locals => {:f=>f}
      #button_container
        #next_submit=image_submit_tag "next_bl.gif", alt: 'submit ssl certificate order'
        #product_details.center{style: "font-size: 1.5em"}
          =link_to image_tag('more_info_sm_bl.gif', :title=>'click to see this certificate'), certificate_url(@certificate.product_root)
    .domainsParent
      .addGroup
        %input#addInput{:placeholder => "Add a domain", :type => "text", :value => ""}
        %label#add{:type => "label"}
          %b +
      #domains
=render :partial => '/certificates/index_scripts_ucc'

app/views/certificates/pricing.html.erb
durations = new Array(<%=@certificate.num_durations%>);
<%-ratio = @certificate_order.signed_certificates.try(:last) ? @certificate_order.duration_remaining : 1%>
<%c = -1%>
<%@certificate.num_durations.times do |i| -%>
  <%if @certificate.is_ucc?-%>
    durations[<%=i%>] = new Array(<%=@certificate.num_domain_tiers%>);
    <%@certificate.num_domain_tiers.times do |j|%>
      durations[<%=i%>][<%=j%>] = <%=(@certificate.items_by_domains(true)[i][j].price*((j==0)?3:1))*ratio%>;
    <%end%>
  <%else -%>
    durations[<%=i%>] = <%=@certificate.items_by_duration[i].price*ratio%>;
  <%end -%>
<%end -%>
<%if @certificate.is_ucc? || @certificate.is_wildcard?%>
  licenses = new Array(<%=@certificate.num_durations%>);
  <%@certificate.num_durations.times do |i| -%>
    licenses[<%=i%>] = <%=@certificate.items_by_server_licenses[i].price*ratio%>;
  <%end -%>
  domains = <%=@certificate_content.domains.to_s%>;
<%end%>

app/views/certificates/show_free.html.haml
-c={}
-c[:description]="Get your Free Class 1 validated and industrial strength encrypted SSL Certificate from #{community_name}. Our free SSL Certificates have the same encryption strength and browser acceptance rates as the higher assurance validation SSL Certificates."
-c[:keywords]="free ssl, free ssl certificate, free ssl certificates, test ssl certificate"
-c[:title]="#{community_name} offers Free SSL Certificate to encrypt your site immediately"
-c.each do |k, v|
  -content_for k, c[k]
%h3#certificate_crumbs
  =certificate_crumbs
.leftcolb
  .free_ssl_image_container
    =image_tag "free_ssl.jpg"
.right_product_desc
  %h1
    Get 90 days of trusted SSL encryption - FREE!
  %h2.product_description
    Class 1 validation and industry strength encryption at no cost
  .product_description_buy_certificate
    =link_to image_tag('get_bl.gif', :title=>'click to buy this certificate'), buy_certificate_url(@certificate.product_root)
  -duration = @certificate.cached_product_variant_items.first
  .get_free_ssl
    #{duration.price.format}
.bottom_product_desc
  %p
    Nothing beats free, and 90 days of Free SSL encryption with the SSL Site
    Seal is even better! These free certificate have the same encryption
    strength and browser acceptance rates as the higher assurance validation 
    SSL certificates, only they're free. We can offer free ssl certificates
    since only a domain validation check is performed on Free SSL certificates.
  %p
    Because of the lower validation level, these certificates are
    not ideally suited for ecommerce situations or where establishing trust
    value is of the utmost importance (see
    #{link_to "High Assurance", certificate_path(:id=>'high_assurance')} or
    #{link_to "EV SSL", certificate_path(:id=>'ev')} for commercial grade ssl
    certificate) since only a class 1 validation check is performed.
  %p
    However, these certificates work great for smaller, non-ecommerce sites
    such as blogs or free sites. They also work great for development purposes.
    And because they are good for 90 days, you don't need to worry about
    a small timeframe in which to test out ssl functions. You have 90 days to work with a Free SSL certificate!
  %p
    And of course SSL is an essential part of almost all electronic
    transactions involved in
    transmitting sensitive data such as usernames and passwords, credit card
    information, patient data and many other types of private material. So get
    started with a Free SSL Certificate and get secured today!
=render :partial=>'points_and_other_certs'
.product_description_buy_certificate
  =link_to image_tag('get_bl.gif', :title=>'click to buy this certificate'), buy_certificate_url(@certificate.product_root)
.get_free_ssl
  #{duration.price.format}